
const pageElements = Array.from(document.querySelectorAll('moving-text'));
const lineElements = Array.from(document.querySelectorAll('p'));
const wordElements = Array.from(document.querySelectorAll('span'));

export const [pages] = [pageElements];
export const [lines] = [lineElements];
export const [words] = [wordElements];

export const s00Words = words.filter(w => w.id.includes('s00'));
export const s01Words = words.filter(w => w.id.includes('s01'));
export const s02Words = words.filter(w => w.id.includes('s02'));
export const s03Words = words.filter(w => w.id.includes('s03'));
export const s04Words = words.filter(w => w.id.includes('s04'));
export const s05Words = words.filter(w => w.id.includes('s05'));
export const s06Words = words.filter(w => w.id.includes('s06'));
export const s07Words = words.filter(w => w.id.includes('s07'));
export const s08Words = words.filter(w => w.id.includes('s08'));
export const s09Words = words.filter(w => w.id.includes('s09'));
export const s10Words = words.filter(w => w.id.includes('s10'));
export const s11Words = words.filter(w => w.id.includes('s11'));
export const s12Words = words.filter(w => w.id.includes('s12'));
export const s13Words = words.filter(w => w.id.includes('s13'));
export const s14Words = words.filter(w => w.id.includes('s14'));
export const s15Words = words.filter(w => w.id.includes('s15'));
export const s16Words = words.filter(w => w.id.includes('s16'));
export const s17Words = words.filter(w => w.id.includes('s17'));
export const s18Words = words.filter(w => w.id.includes('s18'));
export const s19Words = words.filter(w => w.id.includes('s19'));
export const s20Words = words.filter(w => w.id.includes('s20'));
export const s21Words = words.filter(w => w.id.includes('s21'));
export const s22Words = words.filter(w => w.id.includes('s22'));
export const s23Words = words.filter(w => w.id.includes('s23'));
export const s24Words = words.filter(w => w.id.includes('s24'));
export const s25Words = words.filter(w => w.id.includes('s25'));
export const s26Words = words.filter(w => w.id.includes('s26'));
export const s27Words = words.filter(w => w.id.includes('s27'));
export const s28Words = words.filter(w => w.id.includes('s28'));
export const s29Words = words.filter(w => w.id.includes('s29'));
export const s30Words = words.filter(w => w.id.includes('s30'));
export const s31Words = words.filter(w => w.id.includes('s31'));
export const s32Words = words.filter(w => w.id.includes('s32'));
export const s33Words = words.filter(w => w.id.includes('s33'));
export const s34Words = words.filter(w => w.id.includes('s34'));

export const s00Lines = lines.filter(l => l.id.includes('s00'));
export const s01Lines = lines.filter(l => l.id.includes('s01'));
export const s02Lines = lines.filter(l => l.id.includes('s02'));
export const s03Lines = lines.filter(l => l.id.includes('s03'));
export const s04Lines = lines.filter(l => l.id.includes('s04'));
export const s05Lines = lines.filter(l => l.id.includes('s05'));
export const s06Lines = lines.filter(l => l.id.includes('s06'));
export const s07Lines = lines.filter(l => l.id.includes('s07'));
export const s08Lines = lines.filter(l => l.id.includes('s08'));
export const s09Lines = lines.filter(l => l.id.includes('s09'));
export const s10Lines = lines.filter(l => l.id.includes('s10'));
export const s11Lines = lines.filter(l => l.id.includes('s11'));
export const s12Lines = lines.filter(l => l.id.includes('s12'));
export const s13Lines = lines.filter(l => l.id.includes('s13'));
export const s14Lines = lines.filter(l => l.id.includes('s14'));
export const s15Lines = lines.filter(l => l.id.includes('s15'));
export const s16Lines = lines.filter(l => l.id.includes('s16'));
export const s17Lines = lines.filter(l => l.id.includes('s17'));
export const s18Lines = lines.filter(l => l.id.includes('s18'));
export const s19Lines = lines.filter(l => l.id.includes('s19'));
export const s20Lines = lines.filter(l => l.id.includes('s20'));
export const s21Lines = lines.filter(l => l.id.includes('s21'));
export const s22Lines = lines.filter(l => l.id.includes('s22'));
export const s23Lines = lines.filter(l => l.id.includes('s23'));
export const s24Lines = lines.filter(l => l.id.includes('s24'));
export const s25Lines = lines.filter(l => l.id.includes('s25'));
export const s26Lines = lines.filter(l => l.id.includes('s26'));
export const s27Lines = lines.filter(l => l.id.includes('s27'));
export const s28Lines = lines.filter(l => l.id.includes('s28'));
export const s29Lines = lines.filter(l => l.id.includes('s29'));
export const s30Lines = lines.filter(l => l.id.includes('s30'));
export const s31Lines = lines.filter(l => l.id.includes('s31'));
export const s32Lines = lines.filter(l => l.id.includes('s32'));
export const s33Lines = lines.filter(l => l.id.includes('s33'));
export const s34Lines = lines.filter(l => l.id.includes('s34'));
