
const pageElements = Array.from(document.querySelectorAll('moving-text'));
const lineElements = Array.from(document.querySelectorAll('p'));
const wordElements = Array.from(document.querySelectorAll('span'));

export const [pages] = [pageElements];
export const [lines] = [lineElements];
export const [words] = [wordElements];

export const p00Words = words.filter(w => w.id.includes('p00'));
export const p01Words = words.filter(w => w.id.includes('p01'));
export const p02Words = words.filter(w => w.id.includes('p02'));
export const p03Words = words.filter(w => w.id.includes('p03'));
export const p04Words = words.filter(w => w.id.includes('p04'));
export const p05Words = words.filter(w => w.id.includes('p05'));
export const p06Words = words.filter(w => w.id.includes('p06'));
export const p07Words = words.filter(w => w.id.includes('p07'));
export const p08Words = words.filter(w => w.id.includes('p08'));
export const p09Words = words.filter(w => w.id.includes('p09'));
export const p10Words = words.filter(w => w.id.includes('p10'));
export const p11Words = words.filter(w => w.id.includes('p11'));
export const p12Words = words.filter(w => w.id.includes('p12'));
export const p13Words = words.filter(w => w.id.includes('p13'));
export const p14Words = words.filter(w => w.id.includes('p14'));
export const p15Words = words.filter(w => w.id.includes('p15'));
export const p16Words = words.filter(w => w.id.includes('p16'));
export const p17Words = words.filter(w => w.id.includes('p17'));
export const p18Words = words.filter(w => w.id.includes('p18'));
export const p19Words = words.filter(w => w.id.includes('p19'));
export const p20Words = words.filter(w => w.id.includes('p20'));
export const p21Words = words.filter(w => w.id.includes('p21'));
export const p22Words = words.filter(w => w.id.includes('p22'));
export const p23Words = words.filter(w => w.id.includes('p23'));
export const p24Words = words.filter(w => w.id.includes('p24'));
export const p25Words = words.filter(w => w.id.includes('p25'));
export const p26Words = words.filter(w => w.id.includes('p26'));
export const p27Words = words.filter(w => w.id.includes('p27'));
export const p28Words = words.filter(w => w.id.includes('p28'));
export const p29Words = words.filter(w => w.id.includes('p29'));
export const p30Words = words.filter(w => w.id.includes('p30'));
export const p31Words = words.filter(w => w.id.includes('p31'));
export const p32Words = words.filter(w => w.id.includes('p32'));
export const p33Words = words.filter(w => w.id.includes('p33'));
export const p34Words = words.filter(w => w.id.includes('p34'));

export const p00Lines = lines.filter(l => l.id.includes('s00'));
export const p01Lines = lines.filter(l => l.id.includes('s01'));
export const p02Lines = lines.filter(l => l.id.includes('s02'));
export const p03Lines = lines.filter(l => l.id.includes('s03'));
export const p04Lines = lines.filter(l => l.id.includes('s04'));
export const p05Lines = lines.filter(l => l.id.includes('s05'));
export const p06Lines = lines.filter(l => l.id.includes('s06'));
export const p07Lines = lines.filter(l => l.id.includes('s07'));
export const p08Lines = lines.filter(l => l.id.includes('s08'));
export const p09Lines = lines.filter(l => l.id.includes('s09'));
export const p10Lines = lines.filter(l => l.id.includes('s10'));
export const p11Lines = lines.filter(l => l.id.includes('s11'));
export const p12Lines = lines.filter(l => l.id.includes('s12'));
export const p13Lines = lines.filter(l => l.id.includes('s13'));
export const p14Lines = lines.filter(l => l.id.includes('s14'));
export const p15Lines = lines.filter(l => l.id.includes('s15'));
export const p16Lines = lines.filter(l => l.id.includes('s16'));
export const p17Lines = lines.filter(l => l.id.includes('s17'));
export const p18Lines = lines.filter(l => l.id.includes('s18'));
export const p19Lines = lines.filter(l => l.id.includes('s19'));
export const p20Lines = lines.filter(l => l.id.includes('s20'));
export const p21Lines = lines.filter(l => l.id.includes('s21'));
export const p22Lines = lines.filter(l => l.id.includes('s22'));
export const p23Lines = lines.filter(l => l.id.includes('s23'));
export const p24Lines = lines.filter(l => l.id.includes('s24'));
export const p25Lines = lines.filter(l => l.id.includes('s25'));
export const p26Lines = lines.filter(l => l.id.includes('s26'));
export const p27Lines = lines.filter(l => l.id.includes('s27'));
export const p28Lines = lines.filter(l => l.id.includes('s28'));
export const p29Lines = lines.filter(l => l.id.includes('s29'));
export const p30Lines = lines.filter(l => l.id.includes('s30'));
export const p31Lines = lines.filter(l => l.id.includes('s31'));
export const p32Lines = lines.filter(l => l.id.includes('s32'));
export const p33Lines = lines.filter(l => l.id.includes('s33'));
export const p34Lines = lines.filter(l => l.id.includes('s34'));
