export { lineWordCountsArray } from './lineWordCountsArray.js'
export { lineReadingTimesArray } from './lineReadingTimes.js'
export { sections, lines, words } from './elements.js'
export { animationOverallDuration } from './animationOverallDuration.js'
export { createAndPauseAnimation } from './createAndPauseAnimation.js'
export { iterateOverStartTime } from './iterateOverStartTime.js'
export { randomNumberGenerator } from './randomNumberGenerator.js'
export { sectionTimelines } from './sectionTimelines.js'
