export { timelines } from './timelines.js'
export { lineWordCountsArray } from './lineWordCountsArray.js'
export { lineReadingTimesArray } from './lineReadingTimes.js'
export { movingTexts, lines, words } from './elements.js'
export { animationOverallDuration } from './animationOverallDuration.js'
export { createAndPauseAnimation } from './createAndPauseAnimation.js'
export { iterateOverStartTime } from './iterateOverStartTime.js'
export { randomNumberGenerator } from './randomNumberGenerator.js'
